config/routes.rb
Ticketee::Application.routes.draw do
  
  root :to => "projects#index"
  
  resources :projects do
    resources :tickets
  end
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :tickets
  validates :name, :presence => true
  
  attr_accessible :name
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  attr_accessible :description, :title
  
  validates :title, :presence => true
  validates :description, :presence => true, :length => {:minimum => 10}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :find_project, :only => [:show, :edit, :update, :destroy]
  
  def index
    @projects = Project.all
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :action=>"new"
    end
  end

  def show
    #@project = Project.find(params[:id])
  end
  
  def edit
    #@project = Project.find(params[:id])
  end
  
  def update
    #@project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render :action => "edit"
    end
  end
  
  def destroy
    #@project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end
  
  
  #private methods down here
  private 
    def find_project
      @project = Project.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
    end
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  
  before_filter :find_project
  before_filter :find_ticket, :only => [:show, :edit, :update, :destroy]
  
  def new
    @ticket = @project.tickets.build
  end
  
  def create
    @ticket = @project.tickets.build(params[:ticket])
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been created."
      render :action => "new"
    end
  end
  
  def show
    
  end
  
  
  
  private
    def find_project
      @project = Project.find(params[:project_id])
    end
  
    def find_ticket
      @ticket = @project.tickets.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ") unless parts.empty?
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
        <%= yield(:title) %>
    <% else %>
        Ticketee
    <% end%>
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <% flash.each do |key, value| %>
        <div class='flash' id='<%= key %>'>
            <%= value %>
        </div>
    
    <% end %>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
    <%= f.error_messages %>
    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </p>
    <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>
<ul>
    <% @projects.each do |project| %>
        <li><%= link_to project.name, project %></li>
    <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<h2><%= @project.name %></h2>
<%= link_to "Edit Project", edit_project_path(@project) %>
<%= link_to "Delete Project", @project, :method => :delete, :data =>{:confirm => "Are you sure you want to delete this project?"} %>
<%= link_to "New Ticket", new_project_ticket_path(@project) %>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>
    <%= f.error_messages %>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %><br />
        <%= f.text_area :description %>
    </p>
    <%= f.submit %>
<% end %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %>

app/views/tickets/show.html.erb
<div id='ticket'>
    <h2><%= @ticket.title %></h2>
    <%= simple_format(@ticket.description) %>
</div>